server:
  port: 8082

spring:
  application:
    name: expense-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/expenses_db}
    username: ${SPRING_DATASOURCE_USERNAME:finance}
    password: ${SPRING_DATASOURCE_PASSWORD:finance}
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

